name: doczen
description: DocZen - Modern Document Management Platform
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  material_color_utilities: ^0.11.1
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  http: ^1.1.0
  dio: ^5.3.2
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^8.0.0
  jwt_decoder: ^2.0.1
  file_picker: ^6.1.1
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  open_file: ^3.3.2
  flutter_animate: ^4.2.0+1
  glassmorphism: ^3.0.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  injectable: ^2.3.2
  firebase_analytics: ^10.7.4
  firebase_core: ^2.24.2
  web_socket_channel: ^2.4.0
  connectivity_plus: ^5.0.2
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  drag_and_drop_lists: ^0.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
